apiVersion: v1
kind: Service
metadata:
 name: react-portfolio-app
spec:
  type: NodePort
  selector:
    app: react-portfolio-app
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 5173
      nodePort: 31000